"use client";

import { useState } from "react";
import Link from "next/link";
import { RefreshCw, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import type { Brief } from "@/lib/analytics/brief";
import { cn } from "@/lib/utils";

export function BriefCard({ initial }: { initial: Brief }) {
  const [brief, setBrief] = useState(initial);
  const [loading, setLoading] = useState(false);

  async function refresh() {
    setLoading(true);
    try {
      const res = await fetch("/api/ai/brief", { method: "POST" });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error);
      setBrief(json);
    } catch (e) {
      toast.error((e as Error).message || "We couldn't refresh the brief right now.");
    } finally {
      setLoading(false);
    }
  }

  const highValueIds = brief.facts.highValueAtRisk.map((c) => c.id);

  return (
    <section className="rounded-lg border bg-surface p-5" aria-label="AI Business Brief">
      <div className="mb-3 flex items-center gap-2">
        <Sparkles className="size-4 text-brand" />
        <h2 className="text-sm font-semibold">AI Business Brief</h2>
        <span className="text-xs text-muted-foreground">
          · {new Date(brief.generatedAt).toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long" })}
        </span>
        <Button variant="ghost" size="icon-sm" className="ml-auto text-muted-foreground" onClick={refresh} disabled={loading} aria-label="Refresh brief">
          <RefreshCw className={cn(loading && "animate-spin")} />
        </Button>
      </div>
      <div className={cn("max-w-3xl space-y-2.5 text-[15px] leading-relaxed text-zinc-700 transition-opacity", loading && "opacity-50")}>
        {brief.text.split(/\n{2,}/).map((p, i) => (
          <p key={i}>{p}</p>
        ))}
      </div>
      {brief.facts.hasData && (
        <div className="mt-4 flex flex-wrap gap-2">
          <Button asChild size="sm" variant="outline">
            <Link href={`/ai?q=${encodeURIComponent("What changed this month?")}`}>View insights</Link>
          </Button>
          {highValueIds.length > 0 && (
            <Button asChild size="sm" variant="ghost">
              <Link href={`/customers?ids=${highValueIds.join(",")}&title=${encodeURIComponent("High-value customers who need attention")}`}>
                See {highValueIds.length} high-value customers
              </Link>
            </Button>
          )}
        </div>
      )}
      {!brief.aiUsed && brief.facts.hasData && (
        <p className="mt-3 text-[11px] text-muted-foreground">Generated by the built-in analysis engine from your data.</p>
      )}
    </section>
  );
}
